get.target.info <- function(){

  target.info = data.table(target= c("Pickhardt",
                                     "Imperiale",
                                     "UKFSS.bysex",
                                     "UKFSS.overall",
                                     "Corley",
                                     "Church",
                                     "Odom",
                                     "Lieberman",
                                     "SEER.all",
                                     "SEER.black"),
                           mix.n=c(1,1,1,1,2,1,1,2,3,2),
                           age.distn.name= 
                                      list("truncated normal",
                                           "truncated normal",
                                           "truncated normal",
                                           "truncated normal",
                                           c("uniform","truncated normal"),
                                           "truncated normal",
                                           "truncated normal",
                                           rep("truncated normal",2),
                                           rep("truncated normal",3),
                                           rep("truncated normal",2)),
                           mix.distn=list(1,1,1,1,c(0.66,0.34),1,1,c(0.83,0.17),c(0.47,0.32,0.21),c(0.54,0.46)),
                           age.parms.fem = list(c(57.42,8.7,40,79.99),
                                                c(59.8,9,50,70.99),
                                                c(59.5,4.44,55,64.99),
                                                c(59.5,4.44,55,64.99),
                                                c(50,69.99,
                                                  72,6.5,70,89.99),
                                                c(65,5,20,90),
                                                c(65,5,20,90),
                                                c(58,7,20,69.99,
                                                  72,6.5,70,99.99),
                                                c(0,35,20,39.99,
                                                  52,18,40,59.99,
                                                  58,16,60,99.99),
                                                c(0,28,20,39.99,
                                                  40,23,40,99.99)),
                           age.parms.male = list(c(57.42,8.7,40,79.99),
                                                 c(59.8,9,50,70.99),
                                                 c(59.5,4.59,55,64.99),	
                                                 c(59.5,4.59,55,64.99),	
                                                 c(50,69.99,
                                                   72,6.5,70,89.99),
                                                 c(65,5,20,90),
                                                 c(65,5,20,90),
                                                 c(58,7,20,69.99,
                                                   72,6.5,70,99.99),
                                                 c(0,35,20,39.99,
                                                   52,18,40,59.99,
                                                   58,16,60,99.99),
                                                 c(0,28,20,39.99,
                                                   40,23,40,99.99)))
return(target.info)
}